# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec2ac3902482e0a41c82ddd6775c8cfafd6fa8d44fa5266c6722a421e0632767a42831ce025462c90cdb1a877e07098b574046e2d3631d46a6b2d7f8d85e0a5d

test:
  secret_key_base: 9b0b1e7d1ff04e688a69745e706720ea66cf5c184528fc7be6424ee3d927de6cb3ca427ee2dbc59e2c9664c05c4b5529ddb45eb0b3a59439372c4b1392f84066

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
